name: Update project version

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '18.X'
      - name: Setup Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Update version
        run: |
          npm version ${{ inputs.version_type }}
      - name: Push version
        run: git push --tags $GIT_PUSH_URL main
        env:
          GIT_PUSH_URL: https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}
