on:
  push:
    branches:
      - main

name: Release the project

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}
    steps:
      - uses: actions/checkout@v4
      - name: Start
        run: |
          echo "The job_id is: $GITHUB_JOB"
      - uses: ./.github/workflows/jobs/update
        with:
          version_type: prerelease

  patch:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'patch') }}
    steps:
      - uses: actions/checkout@v4
      - name: Start
        run: |
          echo "The job_id is: $GITHUB_JOB"
      - uses: ./.github/workflows/jobs/update
        with:
          version_type: prepatch

  minor:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'minor') }}
    steps:
      - uses: actions/checkout@v4
      - name: Start
        run: |
          echo "The job_id is: $GITHUB_JOB"
      - uses: ./.github/workflows/jobs/update
        with:
          version_type: preminor

  major:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'major') }}
    steps:
      - uses: actions/checkout@v4
      - name: Start
        run: |
          echo "The job_id is: $GITHUB_JOB"
      - uses: ./.github/workflows/jobs/update
        with:
          version_type: premajor
