on:
  push:
    branches:
      - main
name: Update package version
jobs:
  release:
    name: Update version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.X'
      - name: Patch version
        if: ${{ contains(github.event.head_commit.message, 'patch') }}
        uses: Reedyuk/NPM-Version@1.2.2
        with:
          version: 'patch'
          git-tag-version: 'true'
      - name: Minor version
        if: ${{ contains(github.event.head_commit.message, 'minor') }}
        uses: Reedyuk/NPM-Version@1.2.2
        with:
          version: 'minor'
          git-tag-version: 'true'
      - name: Major version
        if: ${{ contains(github.event.head_commit.message, 'major') }}
        uses: Reedyuk/NPM-Version@1.2.2
        with:
          version: 'major'
          git-tag-version: 'true'
