on:
  push:
    branches:
      - main
name: Update package version
jobs:
  config:
    name: Configure action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

  release:
    name: Update version with release (1.0.0-x)
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}
    needs:
      - config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.X'
      - name: Prerelease version
        run: npm version prerelease

  patch:
    name: Update version with patch (1.0.x-0)
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'patch') }}
    needs:
      - config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.X'
      - name: Patch version
        run: npm version prepatch

  minor:
    name: Update version with minor (1.x.0-0)
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'minor') }}
    needs:
      - config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.X'
      - name: Minor version
        run: npm version preminor

  major:
    name: Update version with major (x.0.0-0)
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'major') }}
    needs:
      - config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.X'
      - name: Major version
        run: npm version premajor

  push:
    name: Push the version
    runs-on: ubuntu-latest
    needs:
      - release
      - patch
      - minor
      - major
    env:
      GIT_PUSH_URL: https://${{ github.actor }}@github.com/${{ github.repository }}
    steps:
      - name: Push version
        run: git push --tags $GIT_PUSH_URL main
